---

- name: Config the Hyrax App
  hosts: hyrax-demo

  environment:
    RAILS_ENV: '{{ deploy_target }}'

  tasks:

    # TODO: bundle jobs template with ansible_processor_vcpus

    - name: Add Required Gems
      lineinfile:
        path: "{{ app_name }}/Gemfile"
        line: "gem '{{ item }}'"
        state: present
      with_items:
        - hydra-role-management
        - pg
      notify: Bundle Install

    - name: Install Other Gems (via RVM)
      shell: . $HOME/.rvm/scripts/rvm; gem install {{ item }}
      args:
        executable: /bin/bash
      with_items:
        - solr_wrapper
        - fcrepo_wrapper
        - foreverb

    - name: Update database defintions
      template:
        src: '{{ item }}.j2'
        dest: '{{ app_dir }}/config/{{ item }}'
      with_items:
        - database.yml
        - secrets.yml

    - name: Force Migrate
      debug: msg='Forced'
      changed_when: true
      notify: DB Migrate
      when: false

  handlers:
    - name: Bundle Install
      shell: . $HOME/.rvm/scripts/rvm; bundle install --with production --deployment
      args:
        executable: /bin/bash
        chdir: '{{ app_dir }}'
      register: bundle_out
      notify: DB Migrate

    - name: DB Migrate
      shell: . $HOME/.rvm/scripts/rvm; rake db:migrate
      args:
        executable: /bin/bash
        chdir: '{{ app_dir }}'
      register: migrate_out
      notify: migrate output
