---

- name: Create the Hyrax App
  hosts: default

  vars:
    tmpdir: '/tmp'
    app_template: 'template.rb'
    app_name: hyrax
    app_dir: hyrax

  tasks:

    - name: Prepare the Application Template
      copy:
        dest: '{{ tmpdir }}'
        src: template.rb

    - name: Install app
      shell: . .rvm/scripts/rvm; rails _5.0.6_ new '{{ app_name }}' -m '{{ tmpdir ~ '/' ~ app_template }}'
      args:
        executable: /bin/bash
        creates: '{{ app_name }}/Gemfile.lock'
      register: install_out

    - debug:
        var: install_out

    - block:
      #- name: 'Start solr_wrapper'


      - name: '"Start" the server'
        shell: . /home/vagrant/.rvm/scripts/rvm; ./bin/rails hydra:server
        args:
          executable: /bin/bash
          chdir: '{{ app_dir }}'
        changed_when: false
        # this should run forever
        async: 10
        poll: 0
        register: rails_server


      - debug: var=rails_server

      - name: Wait for the port
        wait_for:
          host: localhost
          port: 3000
          delay: 10
          timeout: 30
          state: started
        ignore_errors: true

      - debug: var=rails_server

      - name: Check on the server
        async_status:
          jid: '{{ rails_server.ansible_job_id }}'
        register: server_status

      - debug: var=server_status

      when: false
      # end block
