---

- name: Install RVM and make initial app
  hosts: hyrax-demo

  roles:
    - { role: geerlingguy.repo-epel, become: true }
    - { role: rvm_io.ruby,
        rvm1_rubies: [ "{{ 'ruby-' ~ ruby_version }}" ],
        rvm1_user: "{{ ansible_user_id }}",
        rvm1_install_flags: "--ignore-dotfiles --user-install",
        rvm1_rvm_check_for_updates: false,
        rvm1_ruby_install_flags: "--binary",
      }

  tasks:

    - name: Install Rails the RVM Way
      shell: . .rvm/scripts/rvm; gem install rails --version "{{ rails_version }}" --no-document
      args:
        executable: '/bin/bash'
        creates: .rvm/gems/ruby-{{ ruby_version }}/bin/rails

    - name: Install Hyrax dependencies (CentOS/RHEL/EPEL)
      yum:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - java-1.8.0-openjdk-headless
        - nodejs
        - "{{ postgres_packages }}"
      tags:
        - yum
