---

- name: Install RVM and make initial app
  hosts: default

  roles:
    - { role: rvm_io.ruby, rvm1_rubies: ['2.4.3'], rvm1_user: vagrant }
  tasks:

    - name: Install Rails
      gem:
        name: rails
        state: present
        user_install: yes
      environment:
        PATH: '/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.rvm/bin:/home/vagrant/.local/bin:/home/vagrant/bin'
      register: rails_out
      when: false

    - debug:
      var: rails_out
